export type IColor =
    | "gray"
    | "blue"
    | "indigo"
    | "violet"
    | "pink"
    | "red"
    | "orange"
    | "yellow"
    | "lime"
    | "green"
    | "teal"
    | "cyan"
    | "light"
    | "primary"